name: John Eastland
favicon: null
layout_spectrum: 0.2035446
typography_spectrum: 0.5193341
title: John Eastland - Supply Chain Expert
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e61bb'
    - '#98a4bd'
    - '#1c85e0'
    - '#dbe2ec'
    - '#032568'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 1
purpose: []
