name: John Eastland Executive Profile
favicon: null
layout_spectrum: 0.20281
typography_spectrum: 0.407
title: John Eastland - Supply Chain Executive
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a5bdc7'
    - '#3b464c'
    - '#b06955'
    - '#507280'
    - '#ffffff'
  brandStrength: 0
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
