title: John Eastland - Supply Chain Guru
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0.6875
  lightness: 0.6568206
  brandColors:
    - '#0e61bb'
    - '#98a4bd'
    - '#1c85e0'
    - '#dbe2ec'
    - '#032568'
  rhythmicContrast: 0.5354457
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: John Eastland
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2744361
layout_spectrum: 0.20281
